//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FuhrparkContextEntities : DbContext
    {
        public FuhrparkContextEntities()
            : base("name=FuhrparkContextEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<uebersicht_daten> uebersicht_daten { get; set; }
        public virtual DbSet<view_uebersicht> view_uebersicht { get; set; }
    
        public virtual ObjectResult<GetIndexUebersicht_Result> GetIndexUebersicht()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetIndexUebersicht_Result>("GetIndexUebersicht");
        }
    
        public virtual ObjectResult<GetIndexUebersicht_Result> InsertIndexUebersicht(Nullable<int> id, string kennzeichen, string marke, string modell, string fahrzeughalter, string niederlassung, string kraftstoff, Nullable<bool> neuwagen, string status, Nullable<int> testid)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var kennzeichenParameter = kennzeichen != null ?
                new ObjectParameter("Kennzeichen", kennzeichen) :
                new ObjectParameter("Kennzeichen", typeof(string));
    
            var markeParameter = marke != null ?
                new ObjectParameter("Marke", marke) :
                new ObjectParameter("Marke", typeof(string));
    
            var modellParameter = modell != null ?
                new ObjectParameter("Modell", modell) :
                new ObjectParameter("Modell", typeof(string));
    
            var fahrzeughalterParameter = fahrzeughalter != null ?
                new ObjectParameter("Fahrzeughalter", fahrzeughalter) :
                new ObjectParameter("Fahrzeughalter", typeof(string));
    
            var niederlassungParameter = niederlassung != null ?
                new ObjectParameter("Niederlassung", niederlassung) :
                new ObjectParameter("Niederlassung", typeof(string));
    
            var kraftstoffParameter = kraftstoff != null ?
                new ObjectParameter("Kraftstoff", kraftstoff) :
                new ObjectParameter("Kraftstoff", typeof(string));
    
            var neuwagenParameter = neuwagen.HasValue ?
                new ObjectParameter("Neuwagen", neuwagen) :
                new ObjectParameter("Neuwagen", typeof(bool));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var testidParameter = testid.HasValue ?
                new ObjectParameter("Testid", testid) :
                new ObjectParameter("Testid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetIndexUebersicht_Result>("InsertIndexUebersicht", idParameter, kennzeichenParameter, markeParameter, modellParameter, fahrzeughalterParameter, niederlassungParameter, kraftstoffParameter, neuwagenParameter, statusParameter, testidParameter);
        }
    }
}
